# Generated by Django 2.2 on 2021-03-19 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registr_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='pw',
        ),
    ]
